#
# Checking that required variables are set
#

- name: Checking that required variables are set
  fail: msg="{{ item }} is not defined '{{ {{ item }} }}'"
  when: item is undefined
  with_items:
    - dmg_to_install
